version: '3.9'

services:
  database:
    container_name: database
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: 123
    
  interface:
    container_name: interface
    image: node:lts
    ports:
      - '3000:3000'
    volumes:
      - ./interface/:/srv/react-docker
    working_dir: /srv/react-docker
    command: 'yarn start'