version: '3'

networks:
  agendaLab:
    name: agendaLab
    driver: bridge

services:
  database:
    image: mariadb:latest
    container_name: database
    hostname: database
    ports:
      - '3306:3306'
    volumes:
      - ./database/volume:/var/lib/mysql
    networks:
      - agendaLab
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: agendaLab

  backend:
    image: node:16
    container_name: backend
    hostname: backend
    ports:
      - '3030:3000'
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: yarn start:install:dev
    networks:
      - agendaLab
    environment:
      SECRET_TOKEN_KEY: calegari

  frontend:
    image: node:16
    container_name: frontend
    hostname: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: yarn start:install
    networks:
      - agendaLab